"""Page Module

Revision ID: 6ac931e36b08
Revises: 81861022b750
Create Date: 2019-07-18 15:50:09.421313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac931e36b08'
down_revision = '81861022b750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.String(length=100), nullable=True),
    sa.Column('page_id', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about_page')
    # ### end Alembic commands ###
